services:
  php:
    container_name: disco-php
    image: yiisoftware/yii2-php:8.1-fpm-nginx
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8444:80'
    networks:
      disco_public_net:
        ipv4_address: 192.168.47.50
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/runtime/data/db
    networks:
      disco_public_net:
        ipv4_address: 192.168.47.80
  db:
    container_name: disco-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: disco_db
      POSTGRES_USER: disco
      POSTGRES_PASSWORD: disco
    ports:
      - 5432:5432
    networks:
      disco_public_net:
        ipv4_address: 192.168.47.60
networks:
  disco_public_net:
    name: disco_public_net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.47.0/24

volumes:
  mongodb_data: