version: '2'
services:
  php:
    container_name: discoretail-php
    image: yiisoftware/yii2-php:8.1-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8444:80'
    networks:
      discoretail_public_net:
        ipv4_address: 192.168.47.50
  db:
    container_name: discoretail-db
    image: mysql:8.0.28
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: discoretail_db
    ports:
      - 8010:3306
    networks:
      discoretail_public_net:
        ipv4_address: 192.168.47.60
networks:
  discoretail_public_net:
    name: discoretail_public_net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.47.0/24