version: '3'
services:
  php:
    container_name: disco-php
    image: yiisoftware/yii2-php:8.1-fpm-nginx
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8444:80'
    networks:
      disco_public_net:
        ipv4_address: 192.168.47.50
  db:
    container_name: disco-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: disco_db
      POSTGRES_USER: disco
      POSTGRES_PASSWORD: disco
    ports:
      - 5432:5432
    networks:
      disco_public_net:
        ipv4_address: 192.168.47.60
networks:
  disco_public_net:
    name: disco_public_net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.47.0/24